---
title: "Forestplot Tutorial"
author: "STEFANFU"
date: "2023-02-03"
output: html_document
---

## 装包
```{r setup, include=FALSE}
#装包
library(dplyr)
library(knitr)
library(readxl)
library(writexl)
library(grid)
library(magrittr)
library(checkmate)
library(forestplot)
library(readr)
```

## 数据转换
```{r}

#载入数据
setwd("E:/forestplot tutorial")
R_2013 <- read_csv("R_2013.csv")
RT_2013 <- read_csv("RT_2013.csv")

#检查数据
print(R_2013)
print(RT_2013)

#数据合并（为了把他转换成list格式）
combine_2013 <- merge(R_2013,
                      RT_2013,
                      by = c("name", "estimate", "std.error","conf.low", "conf.high", "p.value","model"),
                      all = TRUE) %>%
  filter(!name == "industrial_water_usage")
#转换list格式（f = combine_2013$model 指的是通过合并数据集中的model变量来划分list中的两个子集
mt_list = split(combine_2013, f = combine_2013$model)

#这里就可以看到他list里面包含了两个数据集，一个叫regular一个叫robustness，在之后我们画forestplot的时候我们就可以方便调用
print(mt_list)

```

## 画图
```{r}
#这里tabletext是给forestplot中的一行labeltext指明数据位置的，是在数据的第几列，我这里因为不会在图里放estimate或者pvalue所以我才只用第一行，只显示variable name
tabletext <- cbind(mt_list$Regular[,1])

#正式画图
#命令功能说明：1）labeltext = （指明你会展示哪些数据在表格上，如果想要展示pvalue estimate更多数据就需要在tabletext里把cbind(mt_list$Regular[,1])变更为cbind(mt_list$Regular[,1:3])，我的2列3列就是esitimate和pvalue）;2）mean = （指明你的estimate的数值在哪里，画图用）；3）lower和upper，（指明置信区间，画图用）；4）col=，（颜色）；5）xlab = ,(x轴标题)；6）boxsize = ，（图中的方块大小）；7)legend = （分类的颜色标识）需要和fn.ci_norm = 一起使用
forestplot(labeltext = tabletext,
           mean = cbind(mt_list$Regular[,"estimate"],
                        mt_list$Robustness[,"estimate"]),
           lower = cbind(mt_list$Regular[,"conf.low"],
                         mt_list$Robustness[,"conf.low"]),
           upper = cbind(mt_list$Regular[,"conf.high"],
                         mt_list$Robustness[,"conf.high"]),
           col=fpColors(box=c("royalblue", "orange")),
           xlab= "estimate",
           boxsize = .17,
           legend = c("SBM-GML", "SBM-GML Without Undesire Output"),
           #legend_args = fpLegend(pos = list(x=.75, y=0.25), 
           #gp=gpar(col="#CCCCCC", fill="#F9F9F9")),
           fn.ci_norm = c(fpDrawNormalCI, fpDrawCircleCI))
```

## Reference
```{r}
# https://blog.csdn.net/xianyulianxiti/article/details/115262081?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522167524194516800186528809%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=167524194516800186528809&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-1-115262081-null-null.142^v72^insert_down3,201^v4^add_ask&utm_term=%E5%8F%AF%E8%A7%86%E5%8C%96%E5%9B%9E%E5%BD%92&spm=1018.2226.3001.4187

# https://cran.r-project.org/web/packages/forestplot/vignettes/forestplot.html
# https://shixiangwang.github.io/home/cn/post/use-forestplot/

```